//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_64130005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public string MaDG { get; set; }
        public Nullable<int> Diem { get; set; }
        public string BinhLuan { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
        public string MaSach { get; set; }
        public string MaKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
