CREATE DATABASE Project_64130005

USE Project_64130005

CREATE TABLE NHAXUATBAN (
    MANXB VARCHAR(10) PRIMARY KEY,
    TENNXB NVARCHAR(100),
    DIACHI NVARCHAR(200)
);

CREATE TABLE THELOAI (
    MALOAI VARCHAR(10) PRIMARY KEY,
    TENLOAI NVARCHAR(100)
);

CREATE TABLE TACGIA (
    MATG VARCHAR(10) PRIMARY KEY,
    TENTG NVARCHAR(100)
);


CREATE TABLE SACH (
    MASACH VARCHAR(10) PRIMARY KEY,
    TENSACH NVARCHAR(200),
    ISEN NVARCHAR(50),
    NGONNGU NVARCHAR(50),
    MOTA NVARCHAR(500),
    NGAYXUATBAN DATE,
    DONGIA DECIMAL(10, 2),
    ANHSACH NVARCHAR(200),
    SOTRANG INT,
    NGAYTHEM DATE,
    MANXB VARCHAR(10),
    MATG VARCHAR(10),
    FOREIGN KEY (MANXB) REFERENCES NHAXUATBAN(MANXB),
    FOREIGN KEY (MATG) REFERENCES TACGIA(MATG)
);

ALTER TABLE SACH ADD UPDATEAT DATETIME DEFAULT GETDATE()

CREATE TABLE SACH_LOAI(
	MASACH VARCHAR(10),
	MALOAI VARCHAR(10),
	PRIMARY KEY (MALOAI, MASACH),
    FOREIGN KEY (MALOAI) REFERENCES THELOAI(MALOAI),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
)

CREATE TABLE KHACHHANG (
    MAKH VARCHAR(10) PRIMARY KEY,
    HOTENKH NVARCHAR(100),
    EMAIL NVARCHAR(100),
    SDT NVARCHAR(15),
    DIACHI NVARCHAR(200),
    TAIKHOAN NVARCHAR(50),
    MATKHAU NVARCHAR(100)
);

CREATE TABLE THANHTOAN (
    MATT VARCHAR(10) PRIMARY KEY,
    TENTT NVARCHAR(100)
);

CREATE TABLE LOAINV(
	MALOAINV VARCHAR(10) PRIMARY KEY,
	TENLOAINV NVARCHAR(100),
	LUONGCOBAN DECIMAL(10,2)
)

ALTER TABLE NHANVIEN ADD UPDATEAT DATETIME DEFAULT GETDATE()


CREATE TABLE NHANVIEN (
    MANV VARCHAR(10) PRIMARY KEY,
    HON NVARCHAR(50),
    TENNV NVARCHAR(50),
    DIACHI NVARCHAR(200),
    SDT NVARCHAR(15),
    GIOITINH NVARCHAR(10),
    ANH NVARCHAR(200),
    EMAIL NVARCHAR(100),
    MATKHAU NVARCHAR(225),
    CREATEAT DATETIME,
    MALOAINV VARCHAR(10),
    FOREIGN KEY (MALOAINV) REFERENCES LOAINV(MALOAINV)
);



CREATE TABLE DONHANG (
    MAHD VARCHAR(10) PRIMARY KEY,
    NGAYTAO DATE,
    TONGGIA DECIMAL(10, 2),
    TRANGTHAI NVARCHAR(50),
    NGAYGIAO DATE,
    DIACHI NVARCHAR(200),
    TENNGUOINHAN NVARCHAR(100),
    MAKH VARCHAR(10),
	NVDUYETDON VARCHAR(10),
	NVGIAOHANG VARCHAR(10),
	MATT VARCHAR(10),
	FOREIGN KEY (NVGIAOHANG) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY (MATT) REFERENCES THANHTOAN(MATT),
	FOREIGN KEY (NVDUYETDON) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

ALTER TABLE HOADON ADD NGAYDUYET DATETIME DEFAULT GETDATE()

CREATE TABLE CHITIETHD (
    MAHD VARCHAR(10),
    MASACH VARCHAR(10),
    SOLUONG INT,
    DONGIABAN DECIMAL(10, 2),
    PRIMARY KEY (MAHD, MASACH),
    FOREIGN KEY (MAHD) REFERENCES DONHANG(MAHD),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
);

CREATE TABLE DANHGIA (
    MADG VARCHAR(10) PRIMARY KEY,
    MUCDO INT,
    VANBAN NVARCHAR(500),
    THOIGIANDG DATETIME,
	MASACH VARCHAR(10),
	MAKH VARCHAR(10),
	FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

ALTER TABLE SACH
ADD CONSTRAINT DF_SACH_NGAYTHEM DEFAULT GETDATE() FOR NGAYTHEM;

ALTER TABLE DANHGIA
ADD CONSTRAINT DF_DANHGIA_THOIGIANDG DEFAULT GETDATE() FOR THOIGIANDG;

ALTER TABLE DONHANG
ADD CONSTRAINT DF_DONHANG_NGAYTAO DEFAULT GETDATE() FOR NGAYTAO;

ALTER TABLE NHANVIEN
ADD CONSTRAINT DF_NHANVIEN_CREATEAT DEFAULT GETDATE() FOR CREATEAT;


GO
CREATE TRIGGER trg_NVUpdateTime
ON NHANVIEN
AFTER UPDATE
AS
BEGIN
    UPDATE NHANVIEN
    SET UPDATEAT = GETDATE()
    WHERE MANV IN (SELECT DISTINCT MANV FROM INSERTED);
END;

GO
CREATE TRIGGER trg_SachUpdateTime
ON SACH
AFTER UPDATE
AS
BEGIN
    UPDATE SACH
    SET UPDATEAT = GETDATE()
    WHERE MASACH IN (SELECT DISTINCT MASACH FROM INSERTED);
END;

